### PR TITLE
Make APIs dependency injection friendly

### PR DESCRIPTION
**Pull request by WesleyMiller1998**
This change is ultimately kind of small. The biggest thing is that baseUrl is no longer in the APIs and instead we rely on the BaseAddress being set on the HttpClient. This allows us to inject using the follow format
```
services.AddHttpClient<ISearchApi, SearchApi>(client =>
                    {
                        client.BaseAddress = new Uri(context.Configuration["Endpoints:Indexer"]);
                        client.DefaultRequestHeaders.Add("X-Algo-API-Token", context.Configuration["IndexerToken"]);
                        client.Timeout = Timeout.InfiniteTimeSpan;
                    });
```
I believe this promotes healthy HttpClient use and management and request lifecycle because this format uses IHttpClientFactory instead of individually managed HttpClients on the API objects. My only minor concern with this change is that it slightly merges concerns (the APIs now must access the httpclient to get the baseAddress if they want).

### CODE REVIEW

**Comment by WesleyMiller1998** [comment]
I should add, this style does not prevent API management in the previous form, but it does now allow for injection

**Comment by FrankSzendzielarz** [comment]
OK I tested this and it doesn't quite work. The reason is because of this https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working?rq=1

So, basically in my own tests when passing in https://testnet-algorand.api.purestake.io/ps2 or https://testnet-algorand.api.purestake.io/ps2/ as base address, the HttpClient doesn't like appending a relative URI prefixed with / 

After modifying the API so that the leading "/" is removed, the change works.

Please consider if DI using this syntax 

services.AddHttpClient<IDefaultApi, DefaultApi>(client => client.BaseAddress = new Uri("https://localhost:5001"));

isn't sufficient. If you want, we can go with the above changes, but we have to consider if in the meantime (I mean until I update Algorand's code gen) the approach in this PR doesn't interfere too much with regen (frankly....it doesn't affect it much, but if the above DI syntax is sufficient, then there is no point adding extra work for ourselves)

**Comment by WesleyMiller1998** [comment]
I was unable to replicate the issues you experienced with the leading forward slash, but I also experienced no issues with it removed. I answered this in discord, but for sake of archiving, the reason that this change supports dependency injection is because there is no elegant way to assign the BaseUrl property in ConfigureServices. However, we can easily assign BaseAddress for HttpClients in configure services. There is no additional dependencies with this change and we can leverage the fact that we're providing the host to HttpClientConfigurator.

**Comment by FrankSzendzielarz** [comment]
Agreed on above. Will merge and push to master today.

**Pull request merged**
